// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1qAwrVmYu-cGZzVnwWs54XrvMJDrvbTQ',
    appId: '1:4255827073:web:76b9a03f6ea6d7d9b23980',
    messagingSenderId: '4255827073',
    projectId: 'ai--1-98935',
    authDomain: 'ai--1-98935.firebaseapp.com',
    storageBucket: 'ai--1-98935.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEfm4Q0wtgmL5H_lq-4cACNQ86s_P9ZZQ',
    appId: '1:4255827073:android:24a8522bab57c9a8b23980',
    messagingSenderId: '4255827073',
    projectId: 'ai--1-98935',
    storageBucket: 'ai--1-98935.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe4DSF5ntcRouySbLD-Dd4t3eZ7bi-w9s',
    appId: '1:4255827073:ios:5c2dd085dafd897cb23980',
    messagingSenderId: '4255827073',
    projectId: 'ai--1-98935',
    storageBucket: 'ai--1-98935.firebasestorage.app',
    iosBundleId: 'com.example.clietapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe4DSF5ntcRouySbLD-Dd4t3eZ7bi-w9s',
    appId: '1:4255827073:ios:5c2dd085dafd897cb23980',
    messagingSenderId: '4255827073',
    projectId: 'ai--1-98935',
    storageBucket: 'ai--1-98935.firebasestorage.app',
    iosBundleId: 'com.example.clietapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1qAwrVmYu-cGZzVnwWs54XrvMJDrvbTQ',
    appId: '1:4255827073:web:77ced669e76e806fb23980',
    messagingSenderId: '4255827073',
    projectId: 'ai--1-98935',
    authDomain: 'ai--1-98935.firebaseapp.com',
    storageBucket: 'ai--1-98935.firebasestorage.app',
  );
}
